<?php
$possuiAnterior = isset($this->previous);
$possuiProximaPagina = isset($this->next);
?>
<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php
        if ($possuiAnterior) {
            echo '<li class="page-item"> <a class="page-link" href="' . $this->url(array('page' => $this->previous)) . '" aria-label="Next">
                <span aria-hidden="true">&laquo;</span>
            </a> </li>';
        } else {
            echo '<li class="page-item disabled"> <a class="page-link" href="' . $this->url(array('page' => $this->previous)) . '" aria-label="Next">
                <span aria-hidden="true">&laquo;</span>
            </a> </li>';
        }
        ?>
        <?php foreach ($this->pagesInRange as $page) {
            if ($page == $this->current) {
                echo '<li class="page-item active" aria-current="page">
       <a  class="page-link" href="' . $this->url(array('page' => $page)) . '">' . $page . '</a> 
        </li>';
            } else {
                echo '<li class="page-item" aria-current="page">
       <a  class="page-link" href="' . $this->url(array('page' => $page)) . '">' . $page . '</a> 
        </li>';
            }
        }
        if ($possuiProximaPagina) {
            echo '<li class="page-item"> <a class="page-link" href="' . $this->url(array('page' => $this->next)) . '" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a> </li>';
        } else {
            echo '<li class="page-item disabled"> <a class="page-link" href="' . $this->url(array('page' => $this->next)) . '" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a> </li>';
        }
        ?>

    </ul>
</nav>